modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="pooptrain" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Poop Train" #mandatory
    logoFile="pooptrain.png" #optional
    issueTrackerURL="https://github.com/juh9870/PoopTrain/issues" #optional
    credits="Thanks to authors of Create and Ender Storage mods" #optional
    authors="juh9870" #optional
    description='''Allows Ender Storage chests to be used as a part of Create moving contraptions.'''
[[dependencies.pooptrain]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.pooptrain]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pooptrain]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.5_v0.3.2,)" #keep updated
    ordering="NONE"
    side="BOTH"
[[dependencies.pooptrain]]
    modId="enderstorage"
    mandatory=true
    versionRange="[1.16.5-4.0.3.0,)" #keep updated
    ordering="NONE"
    side="BOTH"