name: Bug report
title: 'Bug report'
labels: [bug]
assignees: []
description: "Report an issue"
body:
- type: textarea
  attributes:
    label: Describe your issue
  validations:
    required: true
- type: input
  attributes:
    label: Mod version
  validations:
    required: true
- type: input
  attributes:
    label: Forge version
  validations:
    required: true
- type: input
  attributes:
    label: Create version
  validations:
    required: true
- type: input
  attributes:
    label: Crash Report
    description: "Paste a link to the crash report, if you crashed."